#:schema node_modules/wrangler/config-schema.json
name = "hooks-automate-builders"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "CC_HOOKS_REGISTRY"
id = "35591743ae8945838b67cfc085a34e9c"
preview_id = "3885bb7384d647e4a2c7076d4f76ec1c"
